# Generated by Django 2.0.6 on 2018-11-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion_Forum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
