# Generated by Django 2.1.2 on 2018-11-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Designing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='timeactual',
            field=models.TimeField(null=True),
        ),
    ]
