# Generated by Django 2.0.6 on 2018-12-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Designing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(),
        ),
    ]
