# Generated by Django 2.0.6 on 2018-11-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Result_Analysis', '0001_initial'),
        ('Test_Designing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_ans', models.IntegerField(default=0)),
                ('wrong_ans', models.IntegerField(default=0)),
                ('marks', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Result_Analysis.Student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Test_Designing.Test')),
            ],
        ),
    ]
