# Generated by Django 2.0.6 on 2018-11-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Designing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='timeactual',
        ),
    ]
