# Generated by Django 2.0.6 on 2018-11-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Designing', '0002_studentresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='exam_duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='test',
            old_name='exam_time',
            new_name='time',
        ),
    ]
