# Generated by Django 2.0.6 on 2018-11-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_Designing', '0002_remove_test_timeactual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time',
            field=models.TimeField(),
        ),
    ]
